export type Category = "Lingerie" | "Swim" | "Jewelry" | "Collection";

export interface Product {
  slug: string;
  name: string;
  price: number;
  compareAt?: number;
  category: Category;
  bundle?: boolean;
  description: string;
  details: string[];
  materials: string;
  sizes: string[] | null;
  /** Label above the selector — "Size" for apparel/rings, "Finish" for metals. */
  sizeLabel?: string;
  images: string[];
}

// Auto-generated by scripts/scan-images.mjs — lists whatever images you've
// dropped into public/products/<color>/. Drop any-named files there; the
// scan runs before every `npm run dev` / build. Falls back to the flat
// filenames below if a folder is empty.
import scanned from "./product-images.json";

const imagesFor = (slug: string, fallback: string[]) => {
  const found = (scanned as Record<string, string[]>)[slug];
  return found && found.length ? found : fallback;
};

export const products: Product[] = [
  /* ---------- The First Four — launch capsule, in campaign order ---------- */
  {
    slug: "the-gold-coast",
    name: "The Gold Coast",
    price: 85,
    category: "Swim",
    description:
      "The white halter bikini from the campaign. Matte Italian fabric, ties that hold, gold hardware that doesn't fade by August.",
    details: [
      "Italian matte lycra, fully lined",
      "Halter top with self-tie straps",
      "Low-rise bottom, delicate side ties",
      "Gold-finish hardware · UPF 50+",
    ],
    materials: "Italian lycra · gold-finish hardware",
    sizes: ["XS", "S", "M", "L"],
    images: imagesFor("the-gold-coast", [
      "/products/swim-1.jpg",
      "/products/swim-2.jpg",
      "/products/swim-3.jpg",
    ]),
  },
  {
    slug: "the-blush-set",
    name: "The Blush Set",
    price: 95,
    category: "Lingerie",
    description:
      "Blush pink lace against black marble. The soft one — scalloped underwire bra and high-cut panty in the house pink.",
    details: [
      "Floral lace, sheer and patterned panels",
      "Underwired bra, structured cups",
      "High-cut panty",
      "Gold hardware, pearl-tone accents",
    ],
    materials: "Floral lace · satin trim · gold hardware",
    sizes: ["XS", "S", "M", "L"],
    images: imagesFor("the-blush-set", [
      "/products/blush-1.jpg",
      "/products/blush-2.jpg",
    ]),
  },
  {
    slug: "the-noir-set",
    name: "The Noir Set",
    price: 105,
    category: "Lingerie",
    description:
      "Deep black lace, sheer where it counts. The one that never photographs badly and never sits in a drawer.",
    details: [
      "Deep black floral lace, semi-sheer",
      "Underwired bra, high-leg panty",
      "Scalloped edges throughout",
      "Gold hardware",
    ],
    materials: "Floral lace · satin trim · gold hardware",
    sizes: ["XS", "S", "M", "L"],
    images: imagesFor("the-noir-set", [
      "/products/noir-1.jpg",
      "/products/noir-2.jpg",
    ]),
  },
  {
    slug: "the-rouge-set",
    name: "The Rouge Set",
    price: 115,
    category: "Lingerie",
    description:
      "The red. Structured cups, high waist, lace that reads as intent. Worn once, remembered longer.",
    details: [
      "Vibrant red floral lace",
      "Underwired bra, structured cups",
      "High-waist panty, satin front panel",
      "Gold hardware",
    ],
    materials: "Floral lace · satin panels · gold hardware",
    sizes: ["XS", "S", "M", "L"],
    images: imagesFor("the-rouge-set", [
      "/products/rouge-1.jpg",
      "/products/rouge-2.jpg",
      "/products/rouge-flat.jpg",
    ]),
  },

  /* ---------- Jewelry — 925 moissanite ---------- */
  {
    slug: "the-cuban-bracelet",
    name: "The Cuban Bracelet",
    price: 159,
    category: "Jewelry",
    sizeLabel: "Finish",
    sizes: ["Silver", "Gold"],
    description:
      "The Cuban link, done in moissanite. Iced across the top, weighted in the hand, in 925 silver or 18k gold finish.",
    details: [
      "925 sterling silver base",
      "Silver (rhodium) or 18k gold finish",
      "Pavé-set moissanite across every link",
      "Secure box clasp with double safety",
    ],
    materials: "Moissanite · 925 silver · rhodium / 18k gold finish",
    images: imagesFor("the-cuban-bracelet", ["/products/cuban-1.jpg"]),
  },
  {
    slug: "the-tennis-bracelet",
    name: "The Tennis Bracelet",
    price: 139,
    category: "Jewelry",
    sizeLabel: "Finish",
    sizes: ["Silver", "Gold"],
    description:
      "A continuous line of moissanite rounds set by hand. The one piece that goes with everything else on this site.",
    details: [
      "Moissanite rounds, full eternity line",
      "925 sterling silver base",
      "Silver (rhodium) or 18k gold finish",
      "Hidden box clasp",
    ],
    materials: "Moissanite · 925 silver · rhodium / 18k gold finish",
    images: imagesFor("the-tennis-bracelet", ["/products/tennis-1.jpg"]),
  },
  {
    slug: "the-eternity-ring",
    name: "The Eternity Ring",
    price: 129,
    category: "Jewelry",
    sizes: ["5", "6", "7", "8", "9"],
    description:
      "Moissanite the whole way around — nothing hidden against the palm. Worn alone or stacked.",
    details: [
      "Full-eternity moissanite band",
      "925 sterling silver, white gold finish",
      "Comfort-fit interior",
      "Sized to order",
    ],
    materials: "Moissanite · 925 silver · white gold finish",
    images: imagesFor("the-eternity-ring", ["/products/eternity-1.jpg"]),
  },
  {
    slug: "the-halo-ring",
    name: "The Halo Ring",
    price: 199,
    category: "Jewelry",
    sizes: ["5", "6", "7", "8", "9"],
    description:
      "A pear-cut centre stone framed in a halo, flanked by pear sides. The proposal piece — moissanite fire, without the moissanite price.",
    details: [
      "Pear-cut moissanite centre, ~2ct",
      "Halo and pear-cut shoulders",
      "925 sterling silver, white gold finish",
      "Arrives in the Glass Tables ring box",
    ],
    materials: "Moissanite · 925 silver · white gold finish",
    images: imagesFor("the-halo-ring", ["/products/halo-1.jpg"]),
  },
  {
    slug: "the-studs",
    name: "The Studs",
    price: 89,
    category: "Jewelry",
    sizes: null,
    description:
      "Round moissanite solitaires, four-prong, on 925 posts. The pair you forget you're wearing until someone asks.",
    details: [
      "Round brilliant moissanite, ~1ct each",
      "Four-prong basket setting",
      "925 sterling silver posts and backs",
      "Hypoallergenic",
    ],
    materials: "Moissanite · 925 silver",
    images: imagesFor("the-studs", ["/products/studs-1.jpg"]),
  },

  /* ---------- The bundle — sold everywhere, listed nowhere ---------- */
  {
    slug: "the-collection",
    name: "The Complete Collection",
    price: 299,
    compareAt: 400,
    category: "Collection",
    bundle: true,
    description:
      "All four — The Gold Coast, The Blush Set, The Noir Set, The Rouge Set — in one size, one box, one decision. The full first drop for less than three sets alone.",
    details: [
      "The Gold Coast — white halter bikini",
      "The Blush Set — pink lace",
      "The Noir Set — black lace",
      "The Rouge Set — red lace",
      "One size across all four · arrives in the lacquer box",
    ],
    materials: "The complete first drop · numbered",
    sizes: ["XS", "S", "M", "L"],
    images: [
      imagesFor("the-rouge-set", ["/products/rouge-1.jpg"])[0],
      imagesFor("the-noir-set", ["/products/noir-1.jpg"])[0],
      imagesFor("the-blush-set", ["/products/blush-1.jpg"])[0],
      imagesFor("the-gold-coast", ["/products/swim-1.jpg"])[0],
    ],
  },
];

/* the shoppable four, campaign order — grids, rails, and related lists use this */
export const catalog = products.filter((p) => !p.bundle);

export const bundleProduct = products.find((p) => p.bundle)!;

export const bundleSavings =
  (bundleProduct.compareAt ?? 0) - bundleProduct.price;

export const getProduct = (slug: string) =>
  products.find((p) => p.slug === slug);

export const formatPrice = (n: number) => `$${n.toLocaleString("en-US")}`;
